%right 'in'
%right LOW
%right ']'
%nonassoc '>' '<' '<=' '>=' '==' '!=' '&&' '||'
%left '.'
%left '??'
%left ident 'not'

expr
  : atom '>' atom
  | atom '<' atom
  | atom '>=' atom
  | atom '<=' atom
  | atom '!=' atom
  | atom '==' atom
  | atom '&&' atom
  | atom '||' atom
  | atom 'in' atom
  | atom '??' atom
  | ap
  | '{{' expr '}}'

ap
  : ident '(' expr ')'
  | 'not' expr
  | atom

atom
  : var
  | requiredField
  | optionalFields
  | range
  | iff
  | json
  | '(' expr ')'

many
  : {- empty -}
  | many(prod) prod

var
  : ident

requiredField
  : atom '.' ident
  | atom '[' '\'' string '\'' ']'
  | atom '[' atom ']'

optionalFields
  : atom '?' many(field) %shift

field
  : '.' ident
  | '[' '\'' string '\'' ']'
  | '[' atom ']'

range
  : '{{' 'range' mident ',' ident ':=' expr '}}' expr '{{' 'end' '}}'

mident
  : '_'
  | ident

iff
  : '{{' 'if' expr '}}' expr elif_exprs '{{' 'else' '}}' expr '{{' 'end' '}}'

elif_exprs
  : {- empty -}
  | elif_exprs elif_expr

elif_expr
  : '{{' 'elif' expr '}}' expr

json
  : string_lit
  | num_lit
  | boolean
  | null
  | array
  | object

string_lit
  : 's"' string_template '"e'
  | 's"' '"e'

string_template
  : string_template '{{' expr '}}'
  | string_template string
  | '{{' expr '}}'
  | string

num_lit
  : number
  | int %prec LOW

boolean
  : 'true'
  | 'false'

null
  : 'null'

array
  : '[' list_elements ']'
  | '[' ']'

list_elements
  : expr
  | list_elements ',' expr

object
  : '{' object_fields '}'
  | '{' '}'

object_fields
  : object_field
  | object_fields ',' object_field

object_field
  : 's"' object_key '"e' ':' expr
  | 's"' '"e' ':' expr

object_key
  : object_key string
  | string